const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
const GET_COUNTRIES_BY_NAME = "GET_COUNTRIES_BY_NAME";
const GET_COUNTRIES_BY_CONTINENT = "GET_COUNTRIES_BY_CONTINENT";
const GET_ACTIVITIES = "GET_ACTIVITIES";

export {
  GET_ALL_COUNTRIES,
  GET_COUNTRY_BY_ID,
  GET_COUNTRIES_BY_NAME,
  GET_COUNTRIES_BY_CONTINENT,
  GET_ACTIVITIES,
};
